{
 "title": "Unifique Speedtest Exporter",
 "description": "Check your current and past Unifique network performance stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({instance=\"speedtest-exporter:3000\"},instance)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values({job=\"speedtest\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Download Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speed_download_bits_per_second{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Download Speed"
    }
   ]
  },
  {
   "title": "Current Upload Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speed_upload_bits_per_second{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Download Speed"
    }
   ]
  },
  {
   "title": "Current Ping Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speed_ping_ms{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Download Speed"
    }
   ]
  },
  {
   "title": "Current Jitter Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speed_jitter_ms{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Download Speed"
    }
   ]
  },
  {
   "title": "Speedtest Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "speed_download_bits_per_second{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Download Speed"
    },
    {
     "expr": "speed_upload_bits_per_second{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Upload Speed"
    }
   ]
  },
  {
   "title": "Ping Latency Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "speed_ping_ms{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Ping"
    },
    {
     "expr": "speed_jitter_ms{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Jitter"
    }
   ]
  }
 ]
}